import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#f8f9fa",
    borderBottomWidth: 1,
    borderBottomColor: "#e9ecef",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  mapContainer: {
    flex: 1,
    position: "relative",
  },
  map: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontSize: 16,
    color: "#666",
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 20,
    width: "100%",
    maxWidth: width * 0.9,
    maxHeight: "90%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#e9ecef",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  closeButton: {
    padding: 4,
  },
  logoutButton: {
    backgroundColor: "#ff4d4f", // ログアウトボタンの背景色
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 5,
  },
  logoutButtonText: {
    color: "#fff", // ログアウトボタンのテキスト色
    fontWeight: "bold",
    fontSize: 14,
  },
  modalBody: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexGrow: 1,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: "white",
    minHeight: 45,
  },
  textArea: {
    height: 120,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: "#e9ecef",
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#6c757d",
    padding: 12,
    borderRadius: 8,
    marginRight: 8,
  },
  cancelButtonText: {
    color: "white",
    textAlign: "center",
    fontWeight: "600",
  },
  submitButton: {
    flex: 1,
    backgroundColor: "#007AFF",
    padding: 12,
    borderRadius: 8,
    marginLeft: 8,
  },
  submitButtonText: {
    color: "white",
    textAlign: "center",
    fontWeight: "600",
  },
  floatingButton: {
    position: "absolute",
    bottom: 30,
    left: "50%",
    marginLeft: -30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#007AFF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 8,
  },
  keyboardAvoidingView: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  messageListContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: height * 0.65, // 下部をしっかり伸ばすために65%に増加
    minHeight: 400, // 最小高さを設定
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 1001,
    paddingBottom: 0, // 下部のパディングを削除してしっかり伸ばす
  },
  handleBar: {
    width: 40,
    height: 4,
    backgroundColor: "#ddd",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 8,
    marginBottom: 8,
  },
  handleBarContainer: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  handleBarTouchable: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  handleBarIndicator: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  handleBarLine: {
    width: 8,
    height: 1,
    backgroundColor: "#bbb",
    marginHorizontal: 1,
    borderRadius: 0.5,
  },
  messageListHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  messageListTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
  },
  messageList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  messageItemContainer: {
    marginBottom: 8,
  },
  messageItem: {
    flexDirection: "row",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  userIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  messageContent: {
    flex: 1,
    marginRight: 8,
  },
  userName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  messageText: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
    marginBottom: 4,
  },
  messageTime: {
    fontSize: 12,
    color: "#999",
  },
  messageIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconButton: {
    padding: 4,
    marginLeft: 8,
  },
  replyToggle: {
    paddingHorizontal: 52,
    paddingVertical: 8,
  },
  replyToggleText: {
    fontSize: 12,
    color: "#007AFF",
    fontWeight: "500",
  },
  repliesContainer: {
    paddingLeft: 52,
    backgroundColor: "#fafafa",
    borderRadius: 8,
    marginHorizontal: 16,
    marginBottom: 8,
  },
  replyItem: {
    flexDirection: "row",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  replyIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  replyContent: {
    flex: 1,
  },
  replyUserName: {
    fontSize: 12,
    fontWeight: "600",
    color: "#333",
    marginBottom: 2,
  },
  replyText: {
    fontSize: 12,
    color: "#555",
    lineHeight: 16,
    marginBottom: 2,
  },
  replyTime: {
    fontSize: 10,
    color: "#999",
  },
  replyForm: {
    backgroundColor: "#f8f9fa",
    padding: 16,
    marginHorizontal: 16,
    borderRadius: 8,
    marginBottom: 50, // キーボード表示時のマージンを増加
    marginTop: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  replyInput: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    backgroundColor: "white",
    marginBottom: 12,
    minHeight: 70,
    textAlignVertical: "top",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  replyAuthorInput: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    backgroundColor: "white",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  replyFormButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  replyCancel: {
    backgroundColor: "#6c757d",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 4,
    marginRight: 8,
  },
  replyCancelText: {
    color: "white",
    fontSize: 12,
    fontWeight: "600",
  },
  replySubmit: {
    backgroundColor: "#007AFF",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 4,
  },
  replySubmitText: {
    color: "white",
    fontSize: 12,
    fontWeight: "600",
  },
  emptyState: {
    padding: 40,
    alignItems: "center",
  },
  emptyStateText: {
    fontSize: 16,
    color: "#999",
    textAlign: "center",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  imagePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#007AFF",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  imagePickerText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
    marginRight: 8,
  },
  imageRemoveButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "red",
    justifyContent: "center",
    alignItems: "center",
  },
  selectedImage: {
    width: "100%",
    height: 200,
    borderRadius: 12,
    marginTop: 8,
  },
  messageImage: {
    width: "100%",
    height: 150,
    borderRadius: 8,
    marginTop: 8,
    marginBottom: 4,
  },
  reactionsDisplay: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 52,
    paddingVertical: 4,
    marginBottom: 4,
  },
  reactionItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 6,
    marginBottom: 4,
  },
  reactionItemActive: {
    backgroundColor: "#e3f2fd",
    borderWidth: 1,
    borderColor: "#2196f3",
  },
  reactionEmoji: {
    fontSize: 14,
    marginRight: 4,
  },
  reactionCount: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
  },
  replyActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  replyActionButton: {
    padding: 4,
    marginLeft: 4,
  },
  replyReactionsDisplay: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingLeft: 40,
    paddingRight: 12,
    paddingVertical: 4,
  },
  replyReactionItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginRight: 4,
    marginBottom: 2,
  },

  // Web用スタイル
  webMapPlaceholder: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    padding: 20,
  },
  webMapText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#666",
    marginTop: 10,
    textAlign: "center",
  },
  webMapSubtext: {
    fontSize: 14,
    color: "#999",
    marginTop: 5,
    marginBottom: 20,
    textAlign: "center",
  },
  webPostsList: {
    width: "100%",
    maxHeight: 300,
  },
  webPostItem: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e1e5e9",
  },
  webPostHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  webPostAuthor: {
    fontWeight: "bold",
    color: "#333",
  },
  webPostTime: {
    fontSize: 12,
    color: "#666",
  },
  webPostContent: {
    fontSize: 14,
    color: "#333",
    marginBottom: 8,
  },
  webPostImage: {
    fontSize: 12,
    color: "#007AFF",
    marginBottom: 4,
  },
  webPostLocation: {
    flexDirection: "row",
    alignItems: "center",
  },
  webPostLocationText: {
    fontSize: 10,
    color: "#666",
    marginLeft: 4,
  },
});
